### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Created ru_ru.json

### CODE REVIEW

**Comment by Fuzss** [comment]
Please move the file to `1.20.4/Common/src/main/resources/assets/resourcepackoverrides/lang/ru_ru.json`.
Everything in `generated` is deleted whenever data generation is run.

**Comment by mpustovoi** [comment]
Done

**Comment by Fuzss** [comment]
The file must be placed in `lang`, not in the namespace root.

**Comment by mpustovoi** [comment]
My bad
Done

**Pull request merged**
